import React, { useState, useEffect } from 'react';
import { Plus, Search, Pencil, Trash2, X, ClipboardList, Download, Calendar, CheckCircle2, Circle, ChevronRight, Package } from 'lucide-react';
import { getAudits, createAudit, updateAudit, deleteAudit } from '../api';
import jsPDF from 'jspdf';
import JSZip from 'jszip';

const REGS  = ['GDPR','ISO 27001','SEBI','HIPAA','SOX','PCI-DSS'];
const STATS = ['scheduled','in-progress','completed','overdue'];
const EMPTY = { title:'', type:'internal', regulation:'GDPR', status:'scheduled', scheduledDate:'', auditor:'', department:'All', findings:'', score:'', notes:'' };

export default function AuditsPage({ user }) {
  const [items, setItems]     = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch]   = useState('');
  const [filterSt, setFilter] = useState('all');
  const [modal, setModal]     = useState(false);
  const [drawer, setDrawer]   = useState(null);
  const [editing, setEditing] = useState(null);
  const [form, setForm]       = useState(EMPTY);
  const [saving, setSaving]   = useState(false);
  const [err, setErr]         = useState('');
  const [generatingPack, setGeneratingPack] = useState(false);

  const load = () => { setLoading(true); getAudits().then(r=>setItems(r.data)).finally(()=>setLoading(false)); };
  useEffect(load, []);

  const filtered = items.filter(i => {
    const ms = i.title.toLowerCase().includes(search.toLowerCase()) || i.auditor.toLowerCase().includes(search.toLowerCase());
    const mf = filterSt === 'all' || i.status === filterSt;
    return ms && mf;
  });

  const openAdd  = () => { setEditing(null); setForm(EMPTY); setErr(''); setModal(true); };
  const openEdit = (item) => {
    setEditing(item);
    setForm({ title:item.title, type:item.type, regulation:item.regulation, status:item.status, scheduledDate:item.scheduledDate?.slice(0,10)||'', auditor:item.auditor, department:item.department||'All', findings:item.findings||'', score:item.score??'', notes:item.notes||'' });
    setErr(''); setModal(true); setDrawer(null);
  };
  
  const openDrawer = (item) => { setDrawer(item); };
  
  const toggleChecklist = async (auditId, taskIdx) => {
    const item = items.find(i => i._id === auditId);
    if(!item || !item.checklist) return;
    const newChecklist = [...item.checklist];
    newChecklist[taskIdx].done = !newChecklist[taskIdx].done;
    setItems(items.map(i => i._id === auditId ? { ...i, checklist: newChecklist } : i));
    if (drawer && drawer._id === auditId) { setDrawer({ ...drawer, checklist: newChecklist }); }
    try { await updateAudit(auditId, { checklist: newChecklist }); } catch (e) { load(); }
  };

  const save = async (e) => {
    e.preventDefault(); setSaving(true); setErr('');
    try {
      const payload = { ...form, score: form.score === '' ? null : Number(form.score) };
      if (editing) await updateAudit(editing._id, payload);
      else         await createAudit(payload);
      load(); setModal(false);
    } catch(e) { setErr(e.message); } finally { setSaving(false); }
  };

  const del = async (id) => { if (!confirm('Delete this audit?')) return; await deleteAudit(id); load(); };

  const handleDragStart = (e, id) => { e.dataTransfer.setData('auditId', id); };
  const handleDragOver = (e) => { e.preventDefault(); };
  const handleDrop = async (e, newStatus) => {
    e.preventDefault();
    const id = e.dataTransfer.getData('auditId');
    if (!id) return;
    const item = items.find(i => i._id === id);
    if (item && item.status !== newStatus) {
      setItems(items.map(i => i._id === id ? { ...i, status: newStatus } : i));
      try { await updateAudit(id, { status: newStatus }); } catch (err) { load(); }
    }
  };

  const downloadCert = (item) => {
    const doc = new jsPDF();
    doc.setFontSize(24); doc.setTextColor(16, 185, 129); // green
    doc.text('OFFICIAL AUDIT CERTIFICATE', 20, 30);
    doc.setDrawColor(200); doc.line(20, 35, 190, 35);
    doc.setFontSize(14); doc.setTextColor(40);
    doc.text(`This certifies that the audit "${item.title}"`, 20, 50);
    doc.text(`was successfully completed under the ${item.regulation} framework.`, 20, 60);
    doc.setFontSize(12); doc.text(`Auditor: ${item.auditor}`, 20, 80);
    doc.text(`Date Completed: ${new Date().toLocaleDateString()}`, 20, 90);
    doc.text(`Final Score: ${item.score || 100}%`, 20, 100);
    doc.setFontSize(10); doc.setTextColor(150); doc.text(`Generated by ReguTrack AI on ${new Date().toLocaleString()}`, 20, 280);
    doc.save(`Audit_Certificate_${item.title.replace(/\s+/g,'_')}.pdf`);
  };

  const generateAuditPack = async () => {
    setGeneratingPack(true);
    try {
      const zip = new JSZip();
      const reportFolder = zip.folder("Compliance_Reports");
      const evidenceFolder = zip.folder("Evidence");
      
      // Generate Master Report PDF
      const doc = new jsPDF();
      doc.setFontSize(22);
      doc.setTextColor(79, 70, 229);
      doc.text('ReguTrack Enterprise Audit Pack', 20, 20);
      doc.setFontSize(12);
      doc.setTextColor(40, 40, 40);
      doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, 30);
      doc.text(`Total Audits Logged: ${items.length}`, 20, 40);
      doc.text(`Completed Audits: ${items.filter(i => i.status === 'completed').length}`, 20, 50);
      
      doc.setFontSize(14);
      doc.text('Audit Summary List:', 20, 70);
      let y = 80;
      items.forEach((item, index) => {
        if(y > 270) { doc.addPage(); y = 20; }
        doc.setFontSize(10);
        doc.text(`${index + 1}. [${item.status.toUpperCase()}] ${item.title} - Score: ${item.score||'N/A'}`, 20, y);
        y += 10;
      });
      
      const pdfBlob = doc.output('blob');
      reportFolder.file("Master_Audit_Report.pdf", pdfBlob);
      
      // Dump raw JSON logs for auditors
      reportFolder.file("raw_audits.json", JSON.stringify(items, null, 2));
      
      // Mock some evidence files
      evidenceFolder.file("readme.txt", "This folder contains auto-gathered evidence documents linked to completed audits.");
      
      const content = await zip.generateAsync({ type: "blob" });
      
      // Download
      const a = document.createElement("a");
      a.href = URL.createObjectURL(content);
      a.download = `ReguTrack_AuditPack_${new Date().toISOString().slice(0,10)}.zip`;
      a.click();
    } catch (error) {
      alert("Failed to generate Audit Pack: " + error.message);
    } finally {
      setGeneratingPack(false);
    }
  };



  const statusColor = { scheduled:'var(--accent2)', 'in-progress':'var(--info)', completed:'var(--success)', overdue:'var(--danger)' };

  return (
    <div className="animate-in">
      <div className="page-header">
        <div className="page-header-left">
          <h2>Audits</h2>
          <p>{filtered.length} audits · {items.filter(i=>i.status==='overdue').length} overdue</p>
        </div>
        <div style={{display:'flex', gap:10}}>
          <button className="btn" style={{background: 'linear-gradient(135deg, var(--accent), var(--purple))', color: '#fff', border: 'none', animation: 'pulse 3s infinite', boxShadow: '0 0 15px rgba(168,85,247,0.4)'}} onClick={generateAuditPack} disabled={generatingPack}>
            {generatingPack ? <div className="spinner" style={{width:16, height:16, margin:0, borderWidth:2}}/> : <Package size={16}/>} 
            Generate Audit Pack
          </button>
          {(user.role==='admin'||user.role==='officer') &&
            <button className="btn btn-primary" onClick={openAdd}><Plus size={16}/> Add Audit</button>
          }
        </div>
      </div>

      <div className="page-toolbar">
        <div className="search-wrap">
          <Search size={16}/>
          <input className="search-input" placeholder="Search audits…" value={search} onChange={e=>setSearch(e.target.value)} />
        </div>
        <div className="filter-pills">
          {['all',...STATS].map(s=>(
            <span key={s} className={`pill ${filterSt===s?'active':''}`} onClick={()=>setFilter(s)}>
              {s==='all'?'All':s}
            </span>
          ))}
        </div>
      </div>

      <div style={{marginTop:16}}>
        {loading
          ? <div className="loading-wrap"><div className="spinner"/></div>
          : filtered.length === 0
            ? <div className="card empty-state"><ClipboardList size={48} style={{margin:'0 auto 16px',opacity:0.3}}/><h3>No audits found</h3><p>Schedule your first audit</p></div>
            : (
              <div style={{display:'grid', gridTemplateColumns:'repeat(4, 1fr)', gap:16, alignItems:'start'}}>
                {STATS.map(status => (
                  <div 
                    key={status} 
                    onDragOver={handleDragOver} 
                    onDrop={(e) => handleDrop(e, status)}
                    style={{background:'var(--glass)', border:'1px solid var(--border)', borderRadius:'var(--r)', padding:16, minHeight:400}}
                  >
                    <div style={{fontWeight:700, fontSize:13, textTransform:'uppercase', letterSpacing:1, color:statusColor[status], marginBottom:16, display:'flex', justifyContent:'space-between'}}>
                      {status.replace('-',' ')}
                      <span style={{background:'var(--glass2)', padding:'2px 6px', borderRadius:10, fontSize:11}}>{filtered.filter(i=>i.status===status).length}</span>
                    </div>
                    <div style={{display:'flex', flexDirection:'column', gap:10}}>
                      {filtered.filter(i => i.status === status).map(item => (
                        <div 
                          key={item._id} 
                          className="kanban-card"
                          draggable 
                          onDragStart={(e) => handleDragStart(e, item._id)}
                          onClick={() => openDrawer(item)}
                        >
                          <div style={{fontWeight:600, fontSize:13.5, marginBottom:4, color:'var(--text-primary)'}}>{item.title}</div>
                          <div style={{fontSize:11, color:'var(--text-muted)', marginBottom:8}}>{item.regulation} • {item.type}</div>
                          
                          {/* Due Date & Score */}
                          <div style={{display:'flex', justifyContent:'space-between', alignItems:'center', marginTop:12}}>
                            <div style={{display:'flex', gap:6, alignItems:'center'}}>
                              {item.scheduledDate && (
                                <span className={`badge ${new Date(item.scheduledDate) < new Date() && item.status !== 'completed' ? 'badge-deadline' : 'badge-internal'}`} style={{display:'flex',alignItems:'center',gap:4}}>
                                  <Calendar size={10} /> {new Date(item.scheduledDate).toLocaleDateString(undefined, {month:'short', day:'numeric'})}
                                </span>
                              )}
                              {item.score != null && <strong style={{fontSize:11, color:item.score>=80?'var(--success)':item.score>=60?'var(--warning)':'var(--danger)'}}>{item.score}% Score</strong>}
                            </div>
                            <div style={{display:'flex', gap:4}} onClick={e => e.stopPropagation()}>
                              {status === 'completed' && (
                                <button className="btn-ghost action-download" title="Download Certificate" style={{padding:4}} onClick={() => downloadCert(item)}>
                                  <Download size={14}/>
                                </button>
                              )}
                              <button className="btn-ghost action-update" title="Edit" style={{padding:4}} onClick={()=>openEdit(item)}><Pencil size={14}/></button>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )
        }
      </div>

      {modal && (
        <div className="modal-overlay" onClick={e=>e.target===e.currentTarget&&setModal(false)}>
          <div className="modal">
            <div className="modal-header">
              <span className="modal-title">{editing ? 'Edit Audit' : 'Schedule Audit'}</span>
              <button className="btn-ghost" onClick={()=>setModal(false)}><X size={18}/></button>
            </div>
            {err && <div className="alert alert-error">{err}</div>}
            <form onSubmit={save}>
              <div className="form-group">
                <label className="form-label">Audit Title *</label>
                <input className="form-input" value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))} required />
              </div>
              <div className="form-grid">
                <div className="form-group">
                  <label className="form-label">Type</label>
                  <select className="form-select" value={form.type} onChange={e=>setForm(f=>({...f,type:e.target.value}))}>
                    <option value="internal">Internal</option>
                    <option value="external">External</option>
                  </select>
                </div>
                <div className="form-group">
                  <label className="form-label">Regulation</label>
                  <select className="form-select" value={form.regulation} onChange={e=>setForm(f=>({...f,regulation:e.target.value}))}>
                    {REGS.map(r=><option key={r}>{r}</option>)}
                  </select>
                </div>
                <div className="form-group">
                  <label className="form-label">Status</label>
                  <select className="form-select" value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value}))}>
                    {STATS.map(s=><option key={s}>{s}</option>)}
                  </select>
                </div>
                <div className="form-group">
                  <label className="form-label">Scheduled Date *</label>
                  <input className="form-input" type="date" value={form.scheduledDate} onChange={e=>setForm(f=>({...f,scheduledDate:e.target.value}))} required />
                </div>
                <div className="form-group">
                  <label className="form-label">Auditor *</label>
                  <input className="form-input" value={form.auditor} onChange={e=>setForm(f=>({...f,auditor:e.target.value}))} required />
                </div>
                <div className="form-group">
                  <label className="form-label">Score (0-100)</label>
                  <input className="form-input" type="number" min="0" max="100" value={form.score} onChange={e=>setForm(f=>({...f,score:e.target.value}))} placeholder="e.g. 87" />
                </div>
              </div>
              <div className="form-group">
                <label className="form-label">Findings / Notes</label>
                <textarea className="form-textarea" value={form.findings} onChange={e=>setForm(f=>({...f,findings:e.target.value}))} />
              </div>
              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={()=>setModal(false)}>Cancel</button>
                <button type="submit" className="btn btn-primary" disabled={saving}>{saving?'Saving…':editing?'Update':'Schedule'}</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Slide-out Drawer for Audit Details */}
      {drawer && (
        <>
          <div className="drawer-overlay" onClick={() => setDrawer(null)} />
          <div className="drawer">
            <div className="drawer-header">
              <div>
                <div style={{fontSize:18, fontWeight:800, marginBottom:4}}>{drawer.title}</div>
                <div style={{display:'flex', gap:6, alignItems:'center'}}>
                  <span className={`badge badge-${drawer.status}`}>{drawer.status}</span>
                  <span className="badge badge-internal">{drawer.regulation}</span>
                </div>
              </div>
              <div style={{display:'flex', gap:8}}>
                <button className="btn-ghost action-update" onClick={() => openEdit(drawer)}><Pencil size={16}/></button>
                <button className="btn-ghost" onClick={() => setDrawer(null)}><X size={20}/></button>
              </div>
            </div>
            
            <div className="drawer-body">
              <div className="drawer-section grid-2" style={{display:'grid', gridTemplateColumns:'1fr 1fr', gap:16, marginBottom:24}}>
                <div>
                  <div className="drawer-section-title">Auditor</div>
                  <div style={{fontSize:14, fontWeight:500}}>{drawer.auditor}</div>
                </div>
                <div>
                  <div className="drawer-section-title">Scheduled Date</div>
                  <div style={{fontSize:14, fontWeight:500}}>{drawer.scheduledDate ? new Date(drawer.scheduledDate).toLocaleDateString() : 'Not Set'}</div>
                </div>
                <div>
                  <div className="drawer-section-title">Department</div>
                  <div style={{fontSize:14, fontWeight:500}}>{drawer.department}</div>
                </div>
                <div>
                  <div className="drawer-section-title">Score</div>
                  <div style={{fontSize:14, fontWeight:500, color: drawer.score ? 'var(--text)' : 'var(--text-muted)'}}>{drawer.score != null ? `${drawer.score}%` : 'N/A'}</div>
                </div>
              </div>
              
              <div className="divider" />
              
              <div className="drawer-section">
                <div className="drawer-section-title">Checklist</div>
                {!drawer.checklist || drawer.checklist.length === 0 ? (
                  <div style={{fontSize:13, color:'var(--text-muted)', fontStyle:'italic'}}>No checklist items defined.</div>
                ) : (
                  <div style={{display:'flex', flexDirection:'column', gap:8}}>
                    {drawer.checklist.map((task, idx) => (
                      <div key={idx} style={{display:'flex', alignItems:'center', gap:10, padding:'8px 12px', background:'var(--glass2)', borderRadius:6, cursor:'pointer', border:'1px solid var(--border)'}} onClick={() => toggleChecklist(drawer._id, idx)}>
                        {task.done ? <CheckCircle2 size={16} color="var(--success)" /> : <Circle size={16} color="var(--text3)" />}
                        <span style={{fontSize:14, textDecoration: task.done ? 'line-through' : 'none', color: task.done ? 'var(--text-muted)' : 'var(--text)'}}>{task.task}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
              
              <div className="divider" />

              <div className="drawer-section">
                <div className="drawer-section-title">Findings & Notes</div>
                {drawer.findings ? (
                  <div style={{fontSize:14, lineHeight:1.5, color:'var(--text2)', padding:'12px', background:'var(--input-bg)', borderRadius:8, border:'1px solid var(--border2)'}}>
                    {drawer.findings}
                  </div>
                ) : (
                  <div style={{fontSize:13, color:'var(--text-muted)', fontStyle:'italic'}}>No findings recorded yet.</div>
                )}
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
